spring.application.name=restfullApiAssignment

spring.datasource.url=jdbc:postgresql://localhost:5432/restapi_db
spring.datasource.username=postgres
spring.datasource.password=mucyo10
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8089
spring.main.allow-bean-definition-overriding=true